/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.com.leonid.common.lib)
    api(libs.org.telegram.telegrambots.meta)
    api(libs.software.amazon.awssdk.ec2)
    api(libs.com.hierynomus.sshj)
    api(libs.software.amazon.awssdk.s3)
    api(libs.software.amazon.awssdk.ssm)
    api(libs.org.projectlombok.lombok)
    runtimeOnly(libs.com.h2database.h2)
}

group = "com.leonid"
version = "0.0.1-SNAPSHOT"
description = "worker-bot"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
