/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.telegram.telegrambots.springboot.longpolling.starter)
    api(libs.org.telegram.telegrambots.client)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.com.leonid.common.lib)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    runtimeOnly(libs.com.h2database.h2)
    runtimeOnly(libs.com.mysql.mysql.connector.j)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    compileOnly(libs.org.projectlombok.lombok)
}

group = "com.leonid"
version = "0.0.1-SNAPSHOT"
description = "hosting-bot"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
